"use client";

import { useLanguage } from '@/contexts/LanguageContext';
import { ArrowLeft, Calendar, TrendingUp, TrendingDown, Activity, AlertTriangle } from 'lucide-react';
import Link from 'next/link';
import { format } from 'date-fns';

interface CoinData {
    id: string;
    symbol: string;
    name: string;
    current_price: number;
    price_change_percentage_24h: number;
}

interface FngData {
    value: string;
    value_classification: string;
    timestamp: string;
}

interface GlobalData {
    market_cap_percentage: {
        btc: number;
        eth: number;
    };
}

interface DailyReportContentProps {
    fng: FngData;
    coins: CoinData[];
    global: GlobalData;
}

export default function DailyReportContent({ fng, coins, global }: DailyReportContentProps) {
    const { t, language } = useLanguage();
    const dateStr = format(new Date(), 'yyyy-MM-dd');

    const btc = coins.find((c) => c.id === 'bitcoin');
    const eth = coins.find((c) => c.id === 'ethereum');

    if (!btc || !eth) return <div>Loading data...</div>;

    const fngValue = parseInt(fng.value);
    const marketSentiment = fng.value_classification; // from API

    // Translation Logic Helpers
    const isBullish = btc.price_change_percentage_24h >= 0;
    const btcChange = Math.abs(btc.price_change_percentage_24h).toFixed(2);

    // Simple localization map for report text (Dynamic generation)
    const reportText = {
        en: {
            back: "Back to Dashboard",
            title: `Crypto Market ${dateStr}: ${marketSentiment} Dominates as Bitcoin ${isBullish ? 'Rises' : 'Dips'}`,
            sentiment_title: "Market Sentiment Analysis",
            sentiment_desc: `Today's crypto market sentiment is defined by **${marketSentiment}**, with the Fear & Greed Index at **${fngValue}**. ${fngValue < 25 ? "Investors are showing signs of extreme panic." : fngValue > 75 ? "The market is potentially overheated." : "The market is in a relatively neutral state."}`,
            key_moves_title: "Key Moves: Bitcoin & Ethereum",
            btc_desc: `**Bitcoin (BTC)** is strictly at **$${btc.current_price.toLocaleString()}**, showing a ${isBullish ? "bullish" : "bearish"} move of ${btcChange}% in 24h. BTC Dominance: ${global.market_cap_percentage.btc.toFixed(1)}%.`,
            eth_desc: `**Ethereum (ETH)** stands at **$${eth.current_price.toLocaleString()}** (${eth.price_change_percentage_24h >= 0 ? '+' : ''}${eth.price_change_percentage_24h.toFixed(2)}%). ETH Dominance: ${global.market_cap_percentage.eth.toFixed(1)}%.`,
            outlook_title: "Market Outlook",
            outlook_desc: isBullish ? "The market shows resilience. If support holds, we may see upward momentum." : "Current dip tests support levels. Watch for volume and institutional flows.",
            footer: "This report was automatically generated by CryptoSentimeter AI."
        },
        ko: {
            back: "대시보드로 돌아가기",
            title: `가상자산 시장 리포트 (${dateStr}): ${fngValue > 50 ? "탐욕" : "공포"} 장세 속 비트코인 ${isBullish ? '상승' : '하락'}`,
            sentiment_title: "시장 심리 분석",
            sentiment_desc: `오늘의 암호화폐 시장 심리는 **${fngValue > 75 ? "극단적 탐욕" : fngValue > 50 ? "탐욕" : fngValue > 25 ? "공포" : "극단적 공포"}** 단계이며, 공포&탐욕 지수는 **${fngValue}**입니다. ${fngValue < 25 ? "투자자들의 극심한 공포가 관측되며, 역발상 매수 기회일 수 있습니다." : fngValue > 75 ? "시장이 과열권에 진입하여 조정 가능성에 유의해야 합니다." : "시장은 비교적 중립적인 상태를 유지하며 방향성을 모색하고 있습니다."}`,
            key_moves_title: "주요 코인 동향: 비트코인 & 이더리움",
            btc_desc: `**비트코인(BTC)**은 현재 **$${btc.current_price.toLocaleString()}**에 거래되고 있으며, 지난 24시간 동안 **${btcChange}% ${isBullish ? "상승" : "하락"}**했습니다. 비트코인 도미넌스는 ${global.market_cap_percentage.btc.toFixed(1)}% 입니다.`,
            eth_desc: `**이더리움(ETH)**은 **$${eth.current_price.toLocaleString()}** (${eth.price_change_percentage_24h >= 0 ? '+' : ''}${eth.price_change_percentage_24h.toFixed(2)}%)을 기록 중입니다. 이더리움 점유율은 ${global.market_cap_percentage.eth.toFixed(1)}% 입니다.`,
            outlook_title: "시장 전망",
            outlook_desc: isBullish ? "시장이 회복세를 보이고 있습니다. 주요 지지선을 지켜낸다면 추가적인 상승 모멘텀을 기대할 수 있습니다." : "현재 조정은 지지선 테스트 단계입니다. 거래량과 기관의 움직임(코인베이스 프리미엄)을 주시해야 합니다.",
            footer: "본 리포트는 CryptoSentimeter AI 엔진이 실시간 데이터를 기반으로 자동 생성했습니다."
        }
    };

    const txt = language === 'ko' ? reportText.ko : reportText.en;

    // Helper to render bold text from markdown-like syntax
    const renderMarkdown = (text: string) => {
        const parts = text.split(/(\*\*.*?\*\*)/g);
        return parts.map((part, index) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <span key={index} className="text-white font-bold">{part.slice(2, -2)}</span>;
            }
            return part;
        });
    };

    return (
        <article className="prose prose-invert prose-lg max-w-none">
            <Link href="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary transition-colors mb-8 no-underline">
                <ArrowLeft className="w-4 h-4 mr-2" />
                {txt.back}
            </Link>

            <header className="mb-12 border-b border-white/10 pb-8">
                <div className="flex items-center gap-2 text-primary text-sm font-semibold mb-4">
                    <Calendar className="w-4 h-4" />
                    <span>Daily Crypto Market Report</span>
                </div>
                <h1 className="text-3xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400 mb-4 leading-tight">
                    {txt.title}
                </h1>
                <div className="flex items-center gap-4 text-muted-foreground text-sm">
                    <span>By CryptoSentimeter AI</span>
                    <span>•</span>
                    <span>{dateStr}</span>
                </div>
            </header>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-2">
                    <Activity className="text-blue-400" /> {txt.sentiment_title}
                </h2>
                <div className="glass-card p-6 rounded-2xl mb-6">
                    <p className="text-lg leading-relaxed text-gray-300">
                        {renderMarkdown(txt.sentiment_desc)}
                    </p>
                </div>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-2">
                    {isBullish ? <TrendingUp className="text-green-400" /> : <TrendingDown className="text-red-400" />}
                    {txt.key_moves_title}
                </h2>
                <p className="text-gray-300 mb-6 leading-relaxed">
                    {renderMarkdown(txt.btc_desc)}
                </p>
                <p className="text-gray-300 leading-relaxed">
                    {renderMarkdown(txt.eth_desc)}
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-2">
                    <AlertTriangle className="text-orange-400" /> {txt.outlook_title}
                </h2>
                <p className="text-gray-300 leading-relaxed">
                    {txt.outlook_desc}
                </p>
            </section>

            <div className="mt-12 p-6 rounded-2xl bg-gradient-to-r from-cyan-900/20 to-blue-900/20 border border-cyan-500/20">
                <h3 className="text-lg font-bold text-cyan-400 mb-2">Automated Insight</h3>
                <p className="text-sm text-gray-400">
                    {txt.footer}
                </p>
            </div>
        </article>
    );
}
